nome = input("Digite seu nome: ").lower()
novo_nome = nome.replace('a', '')
novo_nome2 = novo_nome.replace('e', '')
novo_nome3 = novo_nome2.replace('i', '')
novo_nome4 = novo_nome3.replace('o', '')
novo_nome5 = novo_nome4.replace('u', '')
print(novo_nome5)